language: python
dist: xenial
python:
  - "3.7"
install:
  - make install
script:
  - make coverage
  - coverage xml
  - coveralls
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "artifacts/build"
  skip_cleanup: true
  draft: true
  on:
    branch: master
    # tags: true
