language: python
dist: xenial
python:
  - "3.7"
jobs:
  include:
  - stage: install
    script: make install-ci
  - stage: test and build
  - name: test
    script:
      - make coverage
      - coverage xml
      - coveralls
  - name: build
    script: make build
  - stage: deploy
    deploy:
      provider: releases
      api_key: $GH_TOKEN
      file: "./artifacts/build"
      skip_cleanup: true
      draft: true
      on:
        branch: master
        # tags: true
