name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        env:
          CI: 1
        run: |
          . script/bootstrap
      - name: Lint
        run: |
          . venv/bin/activate
          invoke lint
      - name: Test
        run: |
          . venv/bin/activate
          invoke test --dev --coverage
      - name: Build
        run: |
          . venv/bin/activate
          invoke build
