name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
      fail-fast: true

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        make install
        . venv/bin/activate
    - name: Lint
      run: |
        invoke lint
    - name: Test
      run: |
        invoke test --coverage
    - name: Build
      run: |
        invoke build
